version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chime-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-km3d8kslxhv3"
s3_prefix = "chime-app"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
